// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reflectMap2FieldNames          = builder.RawFieldNames(&ReflectMap2{})
	reflectMap2Rows                = strings.Join(reflectMap2FieldNames, ",")
	reflectMap2RowsExpectAutoSet   = strings.Join(stringx.Remove(reflectMap2FieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	reflectMap2RowsWithPlaceHolder = strings.Join(stringx.Remove(reflectMap2FieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheShort2ReflectMap2IdPrefix   = "cache:short2:reflectMap2:id:"
	cacheShort2ReflectMap2Md5Prefix  = "cache:short2:reflectMap2:md5:"
	cacheShort2ReflectMap2SurlPrefix = "cache:short2:reflectMap2:surl:"
)

type (
	reflectMap2Model interface {
		Insert(ctx context.Context, data *ReflectMap2) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ReflectMap2, error)
		FindOneByMd5(ctx context.Context, md5 sql.NullString) (*ReflectMap2, error)
		FindOneBySurl(ctx context.Context, surl sql.NullString) (*ReflectMap2, error)
		Update(ctx context.Context, data *ReflectMap2) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultReflectMap2Model struct {
		sqlc.CachedConn
		table string
	}

	ReflectMap2 struct {
		Id       uint64         `db:"id"`        // primary key
		CreateAt time.Time      `db:"create_at"` // create time
		CreateBy string         `db:"create_by"` // create by
		IsDel    uint64         `db:"is_del"`    // soft delete or not ? 0-not delete 1-delete
		Lurl     sql.NullString `db:"lurl"`      // long url
		Md5      sql.NullString `db:"md5"`       // long url md5
		Surl     sql.NullString `db:"surl"`      // short url
		ExpireAt sql.NullTime   `db:"expire_at"` // expire_time
	}
)

func newReflectMap2Model(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultReflectMap2Model {
	return &defaultReflectMap2Model{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`reflect_map2`",
	}
}

func (m *defaultReflectMap2Model) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	short2ReflectMap2IdKey := fmt.Sprintf("%s%v", cacheShort2ReflectMap2IdPrefix, id)
	short2ReflectMap2Md5Key := fmt.Sprintf("%s%v", cacheShort2ReflectMap2Md5Prefix, data.Md5)
	short2ReflectMap2SurlKey := fmt.Sprintf("%s%v", cacheShort2ReflectMap2SurlPrefix, data.Surl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, short2ReflectMap2IdKey, short2ReflectMap2Md5Key, short2ReflectMap2SurlKey)
	return err
}

func (m *defaultReflectMap2Model) FindOne(ctx context.Context, id uint64) (*ReflectMap2, error) {
	short2ReflectMap2IdKey := fmt.Sprintf("%s%v", cacheShort2ReflectMap2IdPrefix, id)
	var resp ReflectMap2
	err := m.QueryRowCtx(ctx, &resp, short2ReflectMap2IdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reflectMap2Rows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReflectMap2Model) FindOneByMd5(ctx context.Context, md5 sql.NullString) (*ReflectMap2, error) {
	short2ReflectMap2Md5Key := fmt.Sprintf("%s%v", cacheShort2ReflectMap2Md5Prefix, md5)
	var resp ReflectMap2
	err := m.QueryRowIndexCtx(ctx, &resp, short2ReflectMap2Md5Key, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `md5` = ? limit 1", reflectMap2Rows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, md5); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReflectMap2Model) FindOneBySurl(ctx context.Context, surl sql.NullString) (*ReflectMap2, error) {
	short2ReflectMap2SurlKey := fmt.Sprintf("%s%v", cacheShort2ReflectMap2SurlPrefix, surl)
	var resp ReflectMap2
	err := m.QueryRowIndexCtx(ctx, &resp, short2ReflectMap2SurlKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `surl` = ? limit 1", reflectMap2Rows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, surl); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReflectMap2Model) Insert(ctx context.Context, data *ReflectMap2) (sql.Result, error) {
	short2ReflectMap2IdKey := fmt.Sprintf("%s%v", cacheShort2ReflectMap2IdPrefix, data.Id)
	short2ReflectMap2Md5Key := fmt.Sprintf("%s%v", cacheShort2ReflectMap2Md5Prefix, data.Md5)
	short2ReflectMap2SurlKey := fmt.Sprintf("%s%v", cacheShort2ReflectMap2SurlPrefix, data.Surl)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, reflectMap2RowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CreateBy, data.IsDel, data.Lurl, data.Md5, data.Surl, data.ExpireAt)
	}, short2ReflectMap2IdKey, short2ReflectMap2Md5Key, short2ReflectMap2SurlKey)
	return ret, err
}

func (m *defaultReflectMap2Model) Update(ctx context.Context, newData *ReflectMap2) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	short2ReflectMap2IdKey := fmt.Sprintf("%s%v", cacheShort2ReflectMap2IdPrefix, data.Id)
	short2ReflectMap2Md5Key := fmt.Sprintf("%s%v", cacheShort2ReflectMap2Md5Prefix, data.Md5)
	short2ReflectMap2SurlKey := fmt.Sprintf("%s%v", cacheShort2ReflectMap2SurlPrefix, data.Surl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, reflectMap2RowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CreateBy, newData.IsDel, newData.Lurl, newData.Md5, newData.Surl, newData.ExpireAt, newData.Id)
	}, short2ReflectMap2IdKey, short2ReflectMap2Md5Key, short2ReflectMap2SurlKey)
	return err
}

func (m *defaultReflectMap2Model) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheShort2ReflectMap2IdPrefix, primary)
}

func (m *defaultReflectMap2Model) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reflectMap2Rows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultReflectMap2Model) tableName() string {
	return m.table
}
