// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reflectMapFieldNames          = builder.RawFieldNames(&ReflectMap{})
	reflectMapRows                = strings.Join(reflectMapFieldNames, ",")
	reflectMapRowsExpectAutoSet   = strings.Join(stringx.Remove(reflectMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	reflectMapRowsWithPlaceHolder = strings.Join(stringx.Remove(reflectMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	reflectMapModel interface {
		Insert(ctx context.Context, data *ReflectMap) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ReflectMap, error)
		FindOneByMd5(ctx context.Context, md5 sql.NullString) (*ReflectMap, error)
		FindOneBySurl(ctx context.Context, surl sql.NullString) (*ReflectMap, error)
		Update(ctx context.Context, data *ReflectMap) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultReflectMapModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ReflectMap struct {
		Id       uint64         `db:"id"`        // primary key
		CreateAt time.Time      `db:"create_at"` // create time
		CreateBy string         `db:"create_by"` // create by
		IsDel    uint64         `db:"is_del"`    // soft delete or not ? 0-not delete 1-delete
		Lurl     sql.NullString `db:"lurl"`      // long url
		Md5      sql.NullString `db:"md5"`       // long url md5
		Surl     sql.NullString `db:"surl"`      // short url
		ExpireAt sql.NullTime   `db:"expire_at"` // expire_time
	}
)

func newReflectMapModel(conn sqlx.SqlConn) *defaultReflectMapModel {
	return &defaultReflectMapModel{
		conn:  conn,
		table: "`reflect_map`",
	}
}

func (m *defaultReflectMapModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultReflectMapModel) FindOne(ctx context.Context, id uint64) (*ReflectMap, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reflectMapRows, m.table)
	var resp ReflectMap
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReflectMapModel) FindOneByMd5(ctx context.Context, md5 sql.NullString) (*ReflectMap, error) {
	var resp ReflectMap
	query := fmt.Sprintf("select %s from %s where `md5` = ? limit 1", reflectMapRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, md5)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReflectMapModel) FindOneBySurl(ctx context.Context, surl sql.NullString) (*ReflectMap, error) {
	var resp ReflectMap
	query := fmt.Sprintf("select %s from %s where `surl` = ? limit 1", reflectMapRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, surl)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReflectMapModel) Insert(ctx context.Context, data *ReflectMap) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, reflectMapRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CreateBy, data.IsDel, data.Lurl, data.Md5, data.Surl, data.ExpireAt)
	return ret, err
}

func (m *defaultReflectMapModel) Update(ctx context.Context, newData *ReflectMap) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, reflectMapRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CreateBy, newData.IsDel, newData.Lurl, newData.Md5, newData.Surl, newData.ExpireAt, newData.Id)
	return err
}

func (m *defaultReflectMapModel) tableName() string {
	return m.table
}
