// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type ConvertRequest struct {
	LongUrl     string `json:"longUrl" validate:"required"`
	UserDef     bool   `json:"userDef,options=true|false,default=false"`
	DefShortUrl string `json:"defShortUrl"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortUrl"`
}

type ShowRequest struct {
	ShortUrl string `path:"shortUrl" validate:"required"`
}

type ShowResponse struct {
	LongUrl string `json:"longUrl"`
}
